### ISSUE TITLE
Screenshot should not be part of the plug-in

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#267]
The screenshot on our `README.md` file is part of the UI plug-in. This is only for our Git repo. It doesn't need to be shipped to users of the plug-in. It should not be stored in any of the plug-ins.

Current location: edu.cuny.hunter.log.ui/icons/screenshot.png

**Comment by saledouble** [comment]
![image](https://user-images.githubusercontent.com/10117031/80380559-bfdd8500-886d-11ea-9fd4-8955a04ad744.png)

**Comment by saledouble** [comment]
Done: 210d00b708c5ce40094becf76ff7a830f51ff531

**Comment by khatchad** [comment]
What are the commits that fixed this problem? I need to see evidence that it is fixed. Moreover, a release needs to be made before this can be closed.

**Comment by khatchad** [comment]
OK, I see you referened https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/commit/210d00b708c5ce40094becf76ff7a830f51ff531, but that is a modification made to the `README.md` file that does not solve this problem. Perhaps you should re-read the issue description?

**Comment by saledouble** [comment]
Fixed by version 1.9.0 https://github.com/ponder-lab/Logging-Level-Evolution-Plugin/releases/tag/v1.9.0
